DelegationsMVC.Web/Controllers/DestinationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DelegationsMVC.Application.Interfaces;
using DelegationsMVC.Application.ViewModels.DestinationVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DelegationsMVC.Web.Controllers
{
    [Authorize( Roles = "Admin, Chief")]
    public class DestinationController : Controller
    {
        private readonly IDestinationService _destService;
        private readonly ILogger<DestinationController> _logger;
        public DestinationController(IDestinationService destService, ILogger<DestinationController> logger)
        {
            _destService = destService;
            _logger = logger;
        }

        [Route("Destination/All")]
        public IActionResult Index()
        {
            var model = _destService.GetAllClients();
            return View(model);
        }

        [HttpGet]
        public IActionResult AddDestination()
        {
            var model = new NewDestinationVm()
            {
                Countries = _destService.GetCountries().ToList()
            };
            return PartialView(model);
        }

        [HttpPost]
        public IActionResult AddDestination(NewDestinationVm destVm)
        {
            if (!ModelState.IsValid)
            {
                destVm.Countries = _destService.GetCountries().ToList();
                return PartialView(destVm);
            }
            var id = _destService.AddDestination(destVm);
            _logger.LogInformation("New destination has been added - " + id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditDestination(int id)
        {
            var model = _destService.GetDestinationForEdit(id);
            if(model == null)
            {
                _logger.LogInformation("Can't edit destination - dosen't exist");
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }

        [HttpPost]
        public IActionResult EditDestination(NewDestinationVm destVm)
        {
            if (!ModelState.IsValid)
            {
                destVm.Countries = _destService.GetCountries().ToList();
                return PartialView(destVm);
            }
            _destService.UpdateDesination(destVm);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteDestination(int id)
        {
            _destService.DeleteDestination(id);
            _logger.LogInformation("Destination " + id + " has been deleted");
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Destination/View/{id}")]
        public IActionResult ViewDestination(int id)
        {
            var model = _destService.GetDestinationDetail(id);
            if (model == null)
            {
                _logger.LogInformation("Can't find destination - " + id + " - dosen't exist");
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [Route("Destination/Project/All")]
        public IActionResult Projects()
        {
            var model = _destService.GetAllProjects();
            return View(model);
        }

        [HttpGet]
        public IActionResult AddProject()
        {
            var model = new NewProjectVm()
            {
                Destinations = _destService.GetDestinations().ToList()
            };
            return PartialView(model);
        }

        [HttpPost]
        public IActionResult AddProject(NewProjectVm projVm)
        {
            if (!ModelState.IsValid)
            {
                projVm.Destinations = _destService.GetDestinations().ToList();
                return PartialView(projVm);
            }
            _destService.AddProject(projVm);
            return RedirectToAction("Projects");
        }

        [HttpGet]
        public IActionResult EditProject(int id)
        {
            var model = _destService.GetProjectForEdit(id);
            if (model == null)
            {
                _logger.LogInformation("Can't edit project - dosen't exist");
                return RedirectToAction("Projects");
            }
            return PartialView(model);
        }

        [HttpPost]
        public IActionResult EditProject(NewProjectVm projVm)
        {
            if (!ModelState.IsValid)
            {
                projVm.Destinations = _destService.GetDestinations().ToList();
                return PartialView(projVm);
            }
            _destService.UpdateProject(projVm);
            return RedirectToAction("Projects");
        }

        [HttpPost]
        public IActionResult DeleteProject(int id)
        {
            _destService.DeleteProject(id);
            _logger.LogInformation("Projects " + id + " has been deleted");
            return RedirectToAction("Projects");
        }

        [HttpPost]
        public IActionResult CloseProject(int id)
        {
            _destService.CloseProject(id);
            _logger.LogInformation("Project " + id + " has been closed");
            return RedirectToAction("Projects");
        }
    }
}

DelegationsMVC.Web/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DelegationsMVC.Application.Interfaces;
using DelegationsMVC.Application.ViewModels.EmployeeVm;
using DelegationsMVC.Web.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;

namespace DelegationsMVC.Web.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _empService;
        private readonly ILogger<EmployeeController> _logger;

        public EmployeeController(IEmployeeService empService, ILogger<EmployeeController> logger)
        {
            _empService = empService;
            _logger = logger;
        }

        [Authorize( Roles = "Accountant, Chief, Admin")]
        [Route("Employee/All")]
        public IActionResult Index()
        {
            var employees = _empService.GetAllEmployeeForList();
            return View(employees);
        }

        /****Employe****/

        [Route("Employee/New")]
        public IActionResult AddEmployee()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (!_empService.CheckIfEmployeeExist(userId))
            {
                return RedirectToAction("ViewEmployee");
            }
            var model = new NewEmployeeVm()
            {
                UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value
            };
            _empService.SetParametersToVm(model);
            return View(model);
        }

        [HttpPost]
        [Route("Employee/New")]
        public IActionResult AddEmployee(NewEmployeeVm model)
        {
            if (!ModelState.IsValid)
            {
                _empService.SetParametersToVm(model);
                return View(model);
            }
            model.Vehicles = _empService.CheckVehiclesList(model.Vehicles);
            model.ContactDetails = _empService.CheckContactsList(model.ContactDetails);
            var id = _empService.AddEmployee(model);
            _logger.LogInformation("New employee has been added - " + id);
            return RedirectToAction("ViewEmployee");
        }

        [HttpGet]
        [Authorize(Roles = "Accountant, Chief, Admin")]
        [Route("Employee/Profile/{id}")]
        public IActionResult ViewEmployee(int id)
        {
            var empVm = _empService.GetEmployeeDetails(id);
            if (empVm == null)
            {
                _logger.LogInformation("Can't show employee details - employee dosen't exist");
                return RedirectToAction("Index");
            }
            return View(empVm);
        }

        [Route ("Employee/Profile")]
        public IActionResult ViewEmployee()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var empVm = _empService.GetEmployeeDetails(userId);
            if(empVm == null)
            {
                _logger.LogInformation("Can't show employee details - employee dosen't exist");
                return RedirectToAction("Index");
            }
            return View(empVm);
        }

        [Route("Employee/EditProfile")]
        public IActionResult EditEmployee()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var empVm = _empService.GetEmployeeForEdit(userId);
            if(empVm == null)
            {
                _logger.LogInformation("Can't edit employee - employee dosen't exist");
                return RedirectToAction("Index");
            }
            _empService.SetParametersToVm(empVm);
            return View(empVm);
        }

        [HttpPost]
        [Route("Employee/EditProfile")]
        public IActionResult EditEmployee(NewEmployeeVm empVm)
        {
            if (!ModelState.IsValid)
            {
                _empService.SetParametersToVm(empVm);
                return View(empVm.Id);
            }
            _empService.UpdateEmployee(empVm);
            return RedirectToAction("ViewEmployee");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            _empService.DeleteEmployee(id);
            _logger.LogInformation("Employee " + id +" has been deleted");
            return RedirectToAction("Index");
        }

        /****Vehicle****/

        public IActionResult NewVehicle()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var model = new NewVehicleVm
            {
                EmployeeId = _empService.GetEmployeeByUserId(userId).Id,
                EngineTypes = _empService.GetEngineTypes().ToList()
            };
            return PartialView("AddNewVehicleForEmployee", model);
        }

        [HttpPost]
        public IActionResult AddNewVehicleForEmployee(NewVehicleVm vehVm)
        {
            if (!ModelState.IsValid)
            {
                vehVm.EngineTypes = _empService.GetEngineTypes().ToList();
                return RedirectToAction("NewVehicle");
            }
            var id = _empService.AddVehicle(vehVm);
            return RedirectToAction("EditEmployee");
        }

        [ServiceFilter(typeof(CheckVehiclePermission))]
        public IActionResult EditVehicle(int id)
        {
            var veh = _empService.GetVehicleForEdit(id);
            if(veh == null)
            {
                _logger.LogInformation("Can't edit vehicle - vehicle dosen't exist");
                return RedirectToAction("EditEmployee");
            }
            veh.EngineTypes = _empService.GetEngineTypes().ToList();
            return PartialView("EditVehicleForEmployee", veh);
        }

        [HttpPost]
        public IActionResult EditVehicleForEmployee(NewVehicleVm vehVm)
        {
            _empService.UpdateVehicle(vehVm);
            return RedirectToAction("EditEmployee");
        }

        [ServiceFilter(typeof(CheckVehiclePermission))]
        public IActionResult DeleteVehicle(int id)
        {
            _empService.DeleteVehicle(id);
            return RedirectToAction("EditEmployee");
        }

        /****Contact****/

        public IActionResult NewContact()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var model = new NewContactDetailsVm
            {
                EmployeeId = _empService.GetEmployeeByUserId(userId).Id,
            ContactDetailTypes = _empService.GetConactDetailTypes().ToList()
            };
            return PartialView("AddNewContactForEmployee", model);
        }

        [HttpPost]
        public IActionResult AddNewContactForEmployee(NewContactDetailsVm conVm)
        {
            var id = _empService.AddContact(conVm);
            return RedirectToAction("EditEmployee");
        }

        [ServiceFilter(typeof(CheckContactPermission))]
        public IActionResult EditContact(int id)
        {
            var model = _empService.GetContactForEdit(id);
            if(model == null)
            {
                _logger.LogInformation("Can't edit contact - contact dosen't exist");
                return RedirectToAction("EditEmployee");
            }
            model.ContactDetailTypes = _empService.GetConactDetailTypes().ToList();
            return PartialView("EditContactForEmployee", model);
        }

        [HttpPost]
        public IActionResult EditContactForEmployee(NewContactDetailsVm con)
        {
            _empService.UpdateContact(con);
            return RedirectToAction("EditEmployee");

        }

        [ServiceFilter(typeof(CheckContactPermission))]
        public IActionResult DeleteContact(int id)
        {
            _empService.DeleteContact(id);
            return RedirectToAction("EditEmployee");
        }
    }
}

DelegationsMVC.Web/Controllers/UserRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DelegationsMVC.Application.Interfaces;
using DelegationsMVC.Application.ViewModels.UserVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DelegationsMVC.Web.Controllers
{
    [Authorize (Roles = "Admin")]
    public class UserRolesController : Controller
    {
        private readonly IUserService _userService;
        public UserRolesController(IUserService userService)
        {
            _userService = userService;
        }

        [Route("Users/All")]
        public IActionResult Index()
        {
            var model = _userService.GetAllUsers();
            return View(model);
        }

        public IActionResult AddRolesToUser(string id)
        {
            var userVm = _userService.GetUserDetails(id);
            return PartialView("AddRolesToUser", userVm);
        }

        [HttpPost]
        public async Task<IActionResult> AddRolesToUser(UserDetailVm user)
        {
            await _userService.ChangeUserRolesAsync(user.Id, user.UserRoles);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteUser(string id)
        {
            await _userService.DeleteUserAsync(id);
            return RedirectToAction("Index");
        }
    }
}

DelegationsMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @using System.Security.Claims;
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DelegationsMVC.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/font-awesome/css/all.css" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Montserrat+Alternates&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-xl navbar-light bg-navbar  box-shadow  mb-3"  role="navigation">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/Logo3.png" height="40" width="220" /></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse flex-sm-row-reverse" id="navbarSupportedContent">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav navbar-collapse justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home iconItem"></i>
                                Home
                            </a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-car iconItem"></i>
                                Delegacje
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Delegation" asp-action="AddDelegation">
                                    <i class="fa fa-plus-square iconItem"></i>
                                    Stwórz
                                </a>
                                <a class="dropdown-item" asp-controller="Delegation" asp-action="CheckWhichUser">
                                    <i class="fas fa-list iconItem"></i>
                                    Twoja lista
                                </a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-id-badge iconItem"></i>
                                Profil
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Employee" asp-action="ViewEmployee">
                                    <i class="fa fa-eye iconItem"></i>
                                    Podgląd
                                </a>
                                <a class="dropdown-item" asp-controller="Employee" asp-action="EditEmployee">
                                    <i class="fa fa-user-edit iconItem"></i>
                                    Edytuj
                                </a>
                            </div>
                        </li>
                        @if (User.IsInRole("Admin") || User.IsInRole("Chief") || User.IsInRole("Accountant"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-users iconItem"></i>
                                    Pracownicy
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Employee" asp-action="Index">
                                        <i class="fa fa-address-book iconItem"></i>
                                        Lista pracowników
                                    </a>
                                    <a class="dropdown-item" asp-controller="Delegation" asp-action="Index">
                                        <i class="fa fa-car iconItem"></i>
                                        Lista delegacji
                                    </a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link" asp-controller="Destination" asp-action="Index" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-building iconItem"></i>
                                    Klienci
                                </a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link" asp-controller="Destination" asp-action="Projects" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-project-diagram iconItem"></i>
                                    Projekty
                                </a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="UserRoles" asp-action="Index">
                                    <i class="fas fa-users iconItem"></i>
                                    Users
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" box-shadow footer text-muted bg-footer">
        <div class="container-fluid row">
            <div class=" col text-md-left">
                <i class="fas fa-copyright iconItem"></i>
                2021 - Delegation system
            </div>
            <div class="col text-md-center">
                Created by Milosz Rzepecki
            </div>
            <div class="col text-md-right">
                <a href="https://www.proautomation.pl/" style="color:white; text-decoration:none">
                    <i class="fas fa-home iconItem" style="font-size:1rem; padding-left:14px"></i>
                    Kontakt
                </a>
                
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>