DelegationsMVC.Web/Controllers/DelegationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DelegationsMVC.Application.Interfaces;
using DelegationsMVC.Application.ViewModels.DelegationVm;
using DelegationsMVC.Application.ViewModels.RouteVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using DelegationsMVC.Web.Filters;
using DelegationsMVC.Web.Helpers;
using IronPdf;

namespace DelegationsMVC.Web.Controllers
{
    [Authorize]
    public class DelegationController : Controller
    {
        private readonly IDelegationService _delegService;
        private readonly IEmployeeService _empService;
        private readonly ILogger<DelegationController> _logger;
        private readonly IHostEnvironment _host;

        public DelegationController(IDelegationService delegService, IEmployeeService empService, ILogger<DelegationController> logger, IHostEnvironment host)
        {
            _delegService = delegService;
            _empService = empService;
            _logger = logger;
            _host = host;
        }

        [Route("Delegation/All")]
        [Authorize(Roles = "Chief, Accountant, Admin")]
        public IActionResult Index()
        {
            
            var delegations = _delegService.GetAllDelegationsForList();
            return View(delegations);
        }

        [Route("Delegation/All/{id}")]
        [ServiceFilter(typeof(CheckEmployeeDelegationPermission))]
        public IActionResult Index(int id)
        {
            var delegations = _delegService.GetDelegationsByEmployee(id);
            return View(delegations);
        }

        public IActionResult CheckWhichUser()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var emp = _empService.GetEmployeeByUserId(userId);
            return RedirectToAction("Index", new { id = emp.Id });
        }

        [Route("Delegation/New")]
        public IActionResult AddDelegation()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if( _empService.CheckIfEmployeeExist(userId) )
            {
                _logger.LogInformation("Can't add delegation - employee dosen't exist");
                return RedirectToAction("AddEmployee", "Employee");
            }
            var model = new NewDelegationVm()
            {
                EmployeeId = _empService.GetEmployeeByUserId(userId).Id
            };
            model = _delegService.SetParametersToVm(model);
            return View(model);
        }

        [HttpPost]
        [Route("Delegation/New")]
        public IActionResult AddDelegation(NewDelegationVm delVm)
        {
            if (!ModelState.IsValid)
            {
                if( delVm.Routes.Count != 3)
                {
                    delVm.Routes.Add(new NewRouteVm());
                }
                delVm = _delegService.SetParametersToVm(delVm);
                return View(delVm);
            }
            var id = _delegService.AddDelegation(delVm);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ServiceFilter(typeof(CheckDelegationPermission))]
        [Route("Delegation/Edit/{id}")]
        public IActionResult EditDelegation(int id)
        {
            var isEditable = _delegService.IsDelegationEditableById(id);
            if (!isEditable)
            {
                return RedirectToAction("ViewDelegation", new { id });
            }
            var del = _delegService.GetDelegationForEdit(id);
            if(del == null)
            {
                _logger.LogInformation("Can't edit delegation - delegation dosen't exist");
                return RedirectToAction("Index");
            }
            _delegService.SetParametersToVm(del);
            return View(del);
        }

        [HttpPost]
        [Route("Delegation/Edit/{id}")]
        public IActionResult EditDelegation(NewDelegationVm del)
        {
            if (!ModelState.IsValid)
            {
                _delegService.SetParametersToVm(del);
                return View(del);
            }
            _delegService.UpdateDelegation(del);
            return RedirectToAction("ViewDelegation", new { id = del.Id });

        }

        [ServiceFilter(typeof(CheckDelegationPermission))]
        public IActionResult DeleteDelegation(int id)
        {
            _delegService.CancelDelegation(id);
            _logger.LogInformation("Delegation " + id + " - has been deleted");
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Delegation/View/{id}")]
        public IActionResult ViewDelegation(int id)
        {
            var del = _delegService.GetDelegationDetails(id);
            if(del == null)
            {
                _logger.LogInformation("Can't show delegation - delegation dosen't exist");
                return RedirectToAction("Index");
            }
            return View(del);
        }

        [ServiceFilter(typeof(CheckDelegationPermission))]
        public IActionResult NewRoute(int id)
        {
            var isEditable = _delegService.IsDelegationEditableById(id);
            var del = _delegService.GetDelegationById(id);
            if (del == null && !isEditable)
            {
                _logger.LogInformation("Can't add new route to the delegation - delegation dosen't exist or is closed");
                return RedirectToAction("Index");
            }

            var model = new NewRouteVm()
            {
                DelegationId = id,
                RouteDetail = new NewRouteDetailVm()
            };
            model = _delegService.SetParametersToVm(model);
            return PartialView("AddNewRouteForDelegation", model);
        }

        [HttpPost]
        public IActionResult AddNewRouteForDelegation(NewRouteVm routeVm)
        {
            if (!ModelState.IsValid)
            {
                _delegService.SetParametersToVm(routeVm);
                return View(routeVm);
            }
            var id = _delegService.AddRoute(routeVm);
            return RedirectToAction("EditDelegation", new { id = routeVm.DelegationId });
        }

        [ServiceFilter(typeof(CheckRoutePermission))]
        public IActionResult DeleteRoute(int idRoute, int idDel)
        {
            var isEditable = _delegService.IsDelegationEditableById(idDel);
            if (!isEditable)
            {
                return RedirectToAction("ViewDelegation", new { id = idDel }); ;
            }
            _delegService.DeleteRoute(idRoute);
            return RedirectToAction("EditDelegation", new { id = idDel });
        }

        [Route("Delegation/EditRoute/{idDel}/{idRoute}")]
        [ServiceFilter(typeof(CheckRoutePermission))]
        public IActionResult EditRoute(int idRoute, int idDel)
        {
            var isEditable = _delegService.IsDelegationEditableById(idDel);
            if (!isEditable)
            {
                return RedirectToAction("ViewDelegation", new { id = idDel });
            }
            var model = _delegService.GetRouteForEdit(idRoute);
            if(model == null)
            {
                _logger.LogInformation("Can't edit route - route dosen't exist");
                return RedirectToAction("EditDelegation", new { id = idDel });
            }
            _delegService.SetParametersToVm(model);
            return PartialView("EditRouteForDelegation", model);
        }

        [HttpPost]
        public IActionResult EditRouteForDelegation(NewRouteVm routeVm)
        {
            if (!ModelState.IsValid)
            {
                _delegService.SetParametersToVm(routeVm);
                return View(routeVm);
            }
            _delegService.UpdateRoute(routeVm);
            return RedirectToAction("EditDelegation", new { id = routeVm.DelegationId });
        }

        [Authorize(Roles = "Chief, Accountant, Admin")]
        public IActionResult AcceptOrPaidDelegation(int delId, int delStatus)
        {
            var isChanged =_delegService.ChangeStatusOfDelegation(delId, delStatus);
            if (!isChanged)
            {
                _logger.LogInformation("Can't change status to Oplacona - accountant acceptance is required/delegation dosen't exists/has demanded status");
                return RedirectToAction("ViewDelegation", new { id = delId });
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Chief, Accountant, Admin")]
        public IActionResult GenerateDelegationReport(int id)
        {
            var model = _delegService.GetDelegationDetails(id);
            Installation.TempFolderPath = $@"{_host.ContentRootPath}/irontemp/";
            Installation.LinuxAndDockerDependenciesAutoConfig = true;
            var html = this.RenderViewAsync("ReportDelegation", model, true);
            var ironPdfRender = new HtmlToPdf();
            ironPdfRender.PrintOptions.CustomCssUrl = new Uri("https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css").ToString();
            var pdfDoc = ironPdfRender.RenderHtmlAsPdf(html.Result);
            return File(pdfDoc.Stream.ToArray(), "application/pdf");
        }
    }
}

DelegationsMVC.Web/Views/Delegation/EditDelegation.cshtml
@model DelegationsMVC.Application.ViewModels.DelegationVm.NewDelegationVm

@{
    ViewData["Title"] = "EditDelegation";
}

<div class="form-row">
    <h1>Edytuj delegację</h1>
</div>

<div class="divRadius">
    <div class="form-row">
        <div class="col-md-8">
            <form asp-action="EditDelegation">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="Id" type="hidden" class="form-control" />
                <div class="form-row">
                    <div class="form-group col">
                        <label asp-for="Purpose" class="control-label">Cel delegacji</label>
                        <input asp-for="Purpose" class="form-control" />
                        <span asp-validation-for="Purpose" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="DestinationId" class="control-label">Miejsce delegacji</label>
                        <select asp-for="DestinationId" asp-items="@(new SelectList(Model.Destinations, "Id", "Name"))" class="form-control"></select>
                        <span asp-validation-for="DestinationId" class="text-danger"></span>
                    </div>
                </div>
                <input asp-for="EmployeeId" type="hidden" class="form-control" />
                <input asp-for="DelegationStatusId" type="hidden" class="form-control" />
                <div class="form-row">
                    <div class="form-group col">
                        <label asp-for="Costs[0].Amount" class="control-label">Noclegi</label>
                        <input asp-for="Costs[0].Amount" class="form-control" />
                        <span asp-validation-for="Costs[0].Amount" class="text-danger"></span>
                        <input type="hidden" asp-for="Costs[0].CostTypeId" value="1" />
                        <input type="hidden" asp-for="Costs[0].CostId" />
                    </div>
                    <div class="form-group col">
                        <label asp-for="Costs[1].Amount" class="control-label">Dodatkowe wydatki</label>
                        <input asp-for="Costs[1].Amount" class="form-control" />
                        <span asp-validation-for="Costs[1].Amount" class="text-danger"></span>
                        <input type="hidden" asp-for="Costs[1].CostTypeId" value="2" />
                        <input type="hidden" asp-for="Costs[1].CostId" />
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Zapisz zmiany" class="btn btn-success" />

                </div>
            </form>
        </div>
    </div>
</div>

<div class="divRadius">
    <div class="form-row">
        <table class="table table-bordered" id="table">
            <thead class="thead-dark">
                <tr>
                    <th>
                        Data wyjazdu
                    </th>
                    <th>
                        Miejsce wyjazdu
                    </th>
                    <th>
                        Data przyjazdu
                    </th>
                    <th>
                        Miejsce przyjazdu
                    </th>
                    <th>
                        Kilometry
                    </th>
                    <th>
                        Akcje
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var route in Model.Routes)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => route.RouteDetail.StartDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => route.RouteDetail.StartPoint)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => route.RouteDetail.EndDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => route.RouteDetail.EndPoint)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => route.RouteDetail.Kilometers)
                        </td>
                        <td>
                            <a class="btn btn-danger btn-sm" href="@Url.Action("DeleteRoute", "Delegation",new { idRoute = route.Id, idDel = route.DelegationId })">
                                <i class="far fa-minus-square iconItem"></i>Usuń</a>
                            <a class="btn btn-info btn-sm" href="javascript:EditRoute(@route.Id,@route.DelegationId,@route.TypeOfTransportId)">
                                <i class="far fa-edit iconItem"></i>
                                Edytuj
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="form-row">
        <input id="AddRoute" type="button" class="btn btn-success" value="Dodaj podróż" onclick="AddRoute()" />
    </div>

    <div id="Route">

    </div>
</div>

<br />
<div class="form-row">
    <a class="btn btn-info" href="@Url.Action("ViewDelegation", "Delegation",new { id= Model.Id })">
        <i class="fas fa-arrow-left iconItem"></i>
    Powrót do delegacji
    </a>
</div>

@section Scripts {

    <script type="text/javascript">

        $(document).ready(function() {
            $('#DeleteForm').hide();
        });

         function AddRoute() {
            var $divRoute = $('#Route');
             $divRoute.empty();
            var url = '@Url.Action("NewRoute","Delegation", new { id = Model.Id} )';
            $divRoute.load(url);
             $('#AddRoute').attr("onclick", "ClearRoute()").attr("value", "Usuń formularz").attr("class", "btn btn-danger");
        }


        function ClearRoute() {
            $('#Route').empty();
            $('#AddRoute').attr("onclick", "AddRoute()").attr("value", "Dodaj podróż").attr("class", "btn btn-success");
            $('#DeleteForm').hide();
        }

        function CheckState() {
            if ($('#TransportTypeSelector').val() == "1") {
                $('#Vehicle').show();
                $('#VehicleSelector').prop('selectedIndex', 0);
            }
            else {
                $('#Vehicle').hide();
                $('#VehicleSelector').val("0");
            }
        }

        function EditRoute(routeId, delId, transportId) {
            ClearRoute();
            var $divRoute = $('#Route');
            var url = '@Url.Action("EditRoute", "Delegation")/' + delId + '/' + routeId;
            $divRoute.load(url, function () {
                if (transportId != 1) {
                    $('#Vehicle').hide();
                }
            });
            $('#AddRoute').attr("onclick", "ClearRoute()").attr("value", "Usuń formularz").attr("class", "btn btn-danger");
        }
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DelegationsMVC.Web/Views/Delegation/Index.cshtml
@model DelegationsMVC.Application.ViewModels.DelegationVm.ListDelegationForListVm

@{
    ViewData["Title"] = "Index";
}

<h1>Lista delegacji pracowników</h1>

@*<p>
        <a asp-action="Create">Create New</a>
    </p>*@
<br />
<div class="divRadius table-responsive">
    <table class="table table-bordered table-striped" id="table" width="100%">
        <thead class="thead-dark">
            <tr>
                <th style="text-align :center">
                    Numer
                </th>
                <th style="text-align :center">
                    Początek
                </th>
                <th style="text-align :center">
                    Koniec
                </th>
                <th style="text-align :center">
                    Miejsce
                </th>
                <th style="text-align :center">
                    Status
                </th>
                <th style="text-align :center">
                    Prezes
                </th>
                <th style="text-align :center">
                    Księgowość
                </th>
                <th style="text-align :center">
                    Szczegóły
                </th>
                <th style="text-align :center">
                    Akcje
                </th>
                @if (User.IsInRole("Accountant") || User.IsInRole("Admin"))
                {
                    <th style="text-align :center">
                        Raport
                    </th>

                }
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Delegations)
            {
                <tr>
                    <td style="text-align :center">
                        @Html.DisplayFor(modelItem => item.DelegationNo)
                    </td>
                    <td style="text-align :center">
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td style="text-align :center">
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td style="text-align :center">
                        @Html.DisplayFor(modelItem => item.Destination)
                    </td>
                    <td style="text-align :center">
                        @Html.DisplayFor(modelItem => item.DelegationStatus)
                    </td>
                    <td style="text-align :center">
                        @Html.DisplayFor(modelItem => item.ChiefApprovedDate)
                    </td>
                    <td style="text-align :center">
                        @Html.DisplayFor(modelItem => item.AccoutantApprovedDate)
                    </td>
                    <td style="text-anchor:middle; text-align :center">
                        <a class="btn btn-info btn-sm" style="margin:5px; width:80px;" href="@Url.Action("ViewDelegation", "Delegation", new { id = item.Id })">
                            <i class="fa fa-info"></i>
                            Pokaż
                        </a>
                        <a class="btn btn-danger btn-sm" style="width: 80px;" href="@Url.Action("DeleteDelegation", "Delegation", new { id = item.Id })">
                            <i class="fas fa-ban"></i>
                        Anuluj
                        </a>
                    </td>
                    <td style="text-anchor:middle; text-align :center">
                        @if (User.IsInRole("Accountant") || User.IsInRole("Admin"))
                        {
                            if (item.AccoutantApprovedDate == null)
                            {
                                <a class="btn btn-success btn-sm" style="margin-bottom:5px; width:100px;" href="@Url.Action("AcceptOrPaidDelegation", "Delegation", new { delId = item.Id, delStatus = 3 })">
                                    <i class="fas fa-check"></i>
                                    Potwierdź
                                </a>
                            }
                            if (item.PaidDateDate == null)
                            {
                                <a class="btn btn-warning btn-sm" style="width:100px;" href="@Url.Action("AcceptOrPaidDelegation", "Delegation", new { delId = item.Id, delStatus = 4 })">
                                    <i class="fas fa-money-bill-wave"></i>
                                    Opłać
                                </a>
                            }

                        }
                        @if (User.IsInRole("Chief"))
                        {
                            if (item.ChiefApprovedDate == null)
                            {
                                <a class="btn btn-success btn-sm" style="margin-top:5px; width:100px;" href="@Url.Action("AcceptOrPaidDelegation", "Delegation", new { delId = item.Id, delStatus = 2 })">
                                    <i class="fas fa-check"></i>
                                    Potwierdź
                                </a>
                            }

                        }
                    </td>
                    @if (User.IsInRole("Accountant") || User.IsInRole("Admin"))
                    {
                        <td style="text-anchor:middle; text-align :center">
                            <a class="btn btn-info btn-sm" style="width: 80px;" href="@Url.Action("GenerateDelegationReport", "Delegation", new { id = item.Id})">
                                <i class="fas fa-file-pdf"></i>
                            Plik
                            </a>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>


@section Scripts{

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchbuilder/1.0.1/css/searchBuilder.dataTables.min.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.6.4/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.flash.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.html5.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.print.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css">
    <script type="text/javascript" language="javascript" src="https://momentjs.com/downloads/moment.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/searchbuilder/1.0.1/js/dataTables.searchBuilder.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/plug-ins/1.10.21/sorting/datetime-moment.js"></script>



    <script type="text/javascript">

        $(document).ready(function () {
            $.fn.dataTable.moment('DD.MM.YYYY HH:mm:ss');
            $('#table').DataTable({
                "scrollX": true,
                responsive: true,
                searchBuilder: {
                    columns: [0, 1, 2, 3, 4, 5, 6]
                },
                dom: 'Qlfrtip',
                "pagingType": "full_numbers",
                "language": {
                    searchBuilder: {
                        add: 'Dodaj filtr',
                        condition: 'Warunek',
                        conditions: {
                            date: {
                                before: 'Przed',
                                after: 'Po',
                                equals: 'Dnia',
                                not: 'Różna od',
                                between: 'Pomiędzy',
                                notBetween: 'Poza',
                                empty: 'Jest pusta',
                                notEmpty: 'Nie jest pusta'
                            },
                            moment: {
                                before: 'Przed',
                                after: 'Po',
                                equals: 'Dnia',
                                not: 'Różna od',
                                between: 'Pomiędzy',
                                notBetween: 'Poza',
                                empty: 'Jest pusta',
                                notEmpty: 'Nie jest pusta'
                            },
                            number: {
                                equals: 'Równe',
                                not: 'Różna od',
                                gt: 'Większa od',
                                gte: 'Większa lub równa od',
                                lt: 'Mniejsza od',
                                lte: 'Mniejsza lub równa od',
                                between: 'Pomiędzy',
                                notBetween: 'Poza',
                                empty: 'Jest pusta',
                                notEmpty: 'Nie jest pusta'
                            },
                            string: {
                                contains: 'Zawiera',
                                empty: 'Jest pusta',
                                notEmpty: 'Nie jest pusta',
                                equals: 'Równa',
                                not: 'Różna od',
                                endsWith: 'Kończy się na',
                                startsWith: 'Zaczyna się od'
                            },
                        },
                        clearAll: 'Wyczyść',
                        deleteTitle: 'Usuń',
                        data: 'Kolumna',
                        leftTitle: 'Lewo',
                        logicAnd: 'oraz',
                        logicOr: 'lub',
                        rightTitle: 'Prawo',
                        title: {
                            0: 'Filtry',
                            _: 'Filtry (%d)'
                        },
                        value: 'Opcja',
                        valueJoiner: 'do'
                    },
                    "lengthMenu": "Pokaż _MENU_ delegacji na stronie",
                    "zeroRecords": "Brak pasujących delegacji",
                    "info": "Strona _PAGE_ z _PAGES_",
                    "infoEmpty": "Brak delegacji w bazie",
                    "infoFiltered": "(przeszukano z _MAX_ liczby rekordów)",
                    "search": "Wyszukaj: ",
                    "select": {
                        "rows": " (%d wybranych)"
                    },
                    "paginate": {
                        "first": "Pierwsza",
                        "last": "Ostatnia",
                        "next": "Następna",
                        "previous": "Poprzednia"
                    },

                },
                buttons: [
                    {
                        extend: 'copyHtml5',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 5, 6]
                        }
                    },
                    {
                        extend: 'excelHtml5',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 5, 6]
                        }
                    },
                    {
                        extend: 'pdfHtml5',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 5, 6]
                        }
                    },
                ],
                "columnDefs": [
                    { "orderable": false, "targets": 7 },
                    { "orderable": false, "targets": 8 },
                    { "orderable": false, "targets": 9 }
                ]
            });
        });
    </script>
}